### ISSUE TITLE
Update sample to match new assistant declaration flavor

### ISSUE THREAD

**Issue by kbeaugrand** [kbeaugrand/SemanticKernel.Assistants#42]
## Desription

Assistant declaration parameters has changed. However samples are not up to date. 

Older ``input_parameter`` paramter is now changed to: 
```yml
input_parameters: 
     - name: <name>
       is_required: True|False
       default_value: ""
       description: |
```

Need to reflect this change to sample provided and readme.
